export const FooterStandardLinks = {
  Admissions: [
    { name: 'Undergraduate', href: 'https://admissions.carleton.ca/' },
    { name: 'Graduate', href: 'https://graduate.carleton.ca/' },
    { name: 'International', href: 'https://admissions.carleton.ca/applicant-type/international-applicants/' },
    { name: 'Professional Development', href: 'https://carleton.ca/future-edge/' },
    { name: 'Financial Aid', href: 'https://carleton.ca/awards/' },
    { name: 'Campus Tours', href: 'https://admissions.carleton.ca/campustours/' },
    { name: 'Initiatives', href: 'https://carleton.ca/cie/' },
  ],
  Academics: [
    { name: 'Schedules & Dates', href: 'https://carleton.ca/academics/schedules-dates/' },
    { name: 'Bightspace', href: 'https://brightspace.carleton.ca/' },
    { name: 'Library', href: 'https://library.carleton.ca/' },
    { name: 'Support Services', href: 'https://carleton.ca/academics/support/' },
    { name: 'Calendars', href: 'https://calendar.carleton.ca/' },
    { name: 'Carleton Online', href: 'https://carleton.ca/cuol/' },
    { name: 'Discovery Centre', href: 'https://carleton.ca/discoverycentre/' },
  ],
  Students: [
    { name: 'Career Services', href: 'https://carleton.ca/career/' },
    { name: 'Dept & Faculties', href: 'https://carleton.ca/academics/' },
    { name: 'Student Email', href: 'https://carleton.ca/ccs/all-services/email/carleton-student-email/' },
    { name: 'Housing', href: 'https://housing.carleton.ca/' },
    { name: "Registrar's Office", href: 'https://carleton.ca/registrar/' },
    { name: 'Registration', href: 'https://carleton.ca/registrar/registration/' },
    { name: 'ITS Help Centre', href: 'https://carleton.ca/its/help-centre/' },
  ],
  Campus: [
    { name: 'Campus Map', href: 'https://carleton.ca/campus/map/' },
    { name: 'Directions', href: 'https://carleton.ca/campus/directions/' },
    { name: 'Events', href: 'https://events.carleton.ca/' },
    { name: 'Parking', href: 'https://carleton.ca/parking/' },
    { name: 'Safety', href: 'https://carleton.ca/safety/' },
    { name: 'Dining Services', href: 'https://dining.carleton.ca/' },
    { name: 'Clubs & Societies', href: 'https://cusaonline.ca/clubs/' },
  ],
  Ravens: [
    { name: 'Giving to Carleton', href: 'https://futurefunder.carleton.ca/' },
    { name: 'Athletics & Recreation', href: 'https://athletics.carleton.ca/' },
    { name: 'GoRavens Varsity', href: 'https://goravens.ca/' },
  ],
}
