import type { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const PrimaryGhost: Story;
export declare const DarkGrey: Story;
export declare const DarkGreyGhost: Story;
export declare const LightGrey: Story;
export declare const GreyGhost: Story;
export declare const White: Story;
export declare const WhiteGhost: Story;
export declare const Disabled: Story;
export declare const Center: Story;
export declare const FullWidth: Story;
export declare const HasIcon: Story;
export declare const SmallButton: Story;
export declare const SmallButtonWithIcon: Story;
export declare const LinkAsSolidButton: Story;
export declare const LinkAsOutlineButton: Story;
//# sourceMappingURL=Button.stories.d.ts.map