export const styles = {
  wrapper: `cu-stackedlist not-contained not-prose mx-auto overflow-hidden rounded-lg bg-white w-full`,
  border: `border border-cu-black-100`,
  shadow: `shadow-lg`,
  oneCol: `grid md:grid-cols-1`,
  twoCol: `grid md:grid-cols-2`,
  offset: `md:mt-4 md:mb-6 duration-300 ease-in`,
  sm: `lg:max-w-md`,
  lg: `lg:max-w-lg`,
  left: `md:float-left lg:ml-2 xl:ml-24 2xl:ml-[15%] md:mr-10 md:max-w-md`,
  right: `md:float-right md:mr-4 xl:mr-24 2xl:mr-[15%] md:ml-10 md:max-w-md`,
  title: `px-6 py-4 text-base md:text-xl font-semibold border-b rounded-t-lg bg-gray-50 text-cu-black-800`,
  div: `p-6`,
  ul: ``,
}
