export const MarketplaceItemData = [
  {
    id: 1,
    title: 'Nintendo 64',
    link: '#',
    cost: '$100.00',
    condition: 'Mint',
    image: 'https://source.unsplash.com/random/400x300',
    alt: 'Image alt tag',
    category: 'category',
  },
  {
    id: 2,
    title: 'Plastic Boxes',
    link: '#',
    cost: '$40.00',
    condition: 'Mint',
    image: 'https://source.unsplash.com/random/400x300',
    alt: 'Image alt tag',
    category: 'category',
  },
  {
    id: 3,
    title: 'Cambridge Audio Stereo Amplifier',
    link: '#',
    cost: '$10000.00',
    condition: 'Open Box',
    image: 'https://source.unsplash.com/random/400x300',
    alt: 'Image alt tag',
    category: 'category',
  },
  {
    id: 4,
    title: 'IKEA Baskets',
    link: '#',
    cost: '$90.00',
    condition: 'Like New',
    image: 'https://source.unsplash.com/random/400x300',
    alt: 'Image alt tag',
    category: 'category',
  },
  {
    id: 5,
    title: 'Hair Collection',
    link: '#',
    cost: '$100.00',
    condition: 'Trash',
    image: 'https://source.unsplash.com/random/400x300',
    alt: 'Image alt tag',
    category: 'category',
  },
]
