export const JobItemData = [
  {
    id: 1,
    title: 'Back End Developer',
    link: '#',
    department: 'Engineering',
    date: 'January 7, 2020',
    dateData: '2020-01-07',
  },
  {
    id: 2,
    title: 'Front End Developer',
    link: '#',
    department: 'Engineering',
    date: 'January 7, 2020',
    dateData: '2020-01-07',
  },
  {
    id: 3,
    title: 'User Interface Designer',
    link: '#',
    department: 'Design',
    date: 'January 14, 2020',
    dateData: '2020-01-14',
  },
  {
    id: 4,
    title: 'Back End Developer',
    link: '#',
    department: 'Engineering',
    date: 'January 7, 2020',
    dateData: '2020-01-07',
  },
  {
    id: 5,
    title: 'Front End Developer',
    link: '#',
    department: 'Engineering',
    date: 'January 7, 2020',
    dateData: '2020-01-07',
  },
]
