import type { Meta, StoryObj } from '@storybook/react';
import { Figure } from './Figure';
declare const meta: Meta<typeof Figure>;
export default meta;
type Story = StoryObj<typeof Figure>;
export declare const ImageFull: Story;
export declare const ImageLarge: Story;
export declare const ImageMedium: Story;
export declare const ImageSmall: Story;
export declare const ImageRounded: Story;
export declare const ImageCircular: Story;
export declare const ImageWithLink: Story;
export declare const ImageWithCaption: Story;
export declare const ImageWithShadow: Story;
export declare const ImageFloatLeft: Story;
export declare const ImageFloatRight: Story;
export declare const ImageCenterAlign: Story;
export declare const Video: Story;
export declare const VideoWithCaption: Story;
//# sourceMappingURL=Figure.stories.d.ts.map