export const EventItemData = [
  {
    id: 1,
    created_at: '2022-11-17T16:36:24.000000Z',
    updated_at: '2022-11-17T16:36:24.000000Z',
    user_id: 100292661,
    title: 'Et ut deserunt ipsum minus.',
    link: '#',
    slug: 'et-ut-deserunt-ipsum-minus',
    featured_image:
      'https://images.unsplash.com/photo-1664618221700-c741183ff4aa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80',
    host_org: 'eveniet quos amet incidunt',
    description:
      'Aut atque quod est doloribus consequatur accusamus. Soluta incidunt excepturi ea sed debitis quaerat quasi cumque. Quis quia saepe enim vel soluta laudantium. Dolores asperiores quos dolores illo necessitatibus amet. Voluptatem repellendus aut id dolore inventore praesentium. Corporis sed deleniti vero alias eos laborum sit.',
    start_date: '2022-12-03 10:27:31',
    end_date: '2022-12-07 03:24:08',
    on_campus: false,
    on_campus_building: null,
    on_campus_room_number: null,
    event_address: '71953 Schmidt Row Apt. 896\nLaurianefurt, TN 88829-0223',
    event_latitude: '-74.748885',
    event_longitude: '-18.754597',
    registration: 0,
    registration_url: null,
    cost: '50.00',
    contact_name: 'Yesenia Larkin',
    contact_number: '+1-283-574-7016',
    contact_email: 'queenie.greenfelder@price.com',
    tags: {
      category: [
        {
          id: 3,
          name: 'Category One',
          slug: 'category-one',
        },
        {
          id: 4,
          name: 'Category Two',
          slug: 'category-two',
        },
      ],
      audience: [
        {
          id: 1,
          name: 'Student',
          slug: 'student',
        },
        {
          id: 2,
          name: 'Faculty',
          slug: 'faculty',
        },
      ],
    },
    multiday: true,
  },
  {
    id: 2,
    created_at: '2022-11-17T16:36:24.000000Z',
    updated_at: '2022-11-17T16:36:24.000000Z',
    user_id: 101096520,
    title: 'Optio qui occaecati odit.',
    link: '#',
    slug: 'optio-qui-occaecati-odit',
    featured_image:
      'https://images.unsplash.com/photo-1654161974932-e26cd97402a1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80',
    host_org: 'necessitatibus vel animi minima sunt',
    description:
      'Commodi et nisi natus dolorem. Est qui quaerat ut maxime. Dolorum expedita et quia veniam. At porro non dolorem aliquam recusandae odit. Omnis explicabo et qui ut molestias debitis.',
    start_date: '2023-02-08 04:29:56',
    end_date: '2023-02-10 10:15:45',
    on_campus: true,
    on_campus_building: 'Robertson Hall',
    on_campus_room_number: '407',
    event_address: '59560 Alford Junction\nLake Wava, CA 80702-6037',
    event_latitude: '82.6912',
    event_longitude: '38.884472',
    registration: 1,
    registration_url:
      'http://www.terry.biz/amet-enim-aut-illo-sit-architecto-libero-in',
    cost: '100.00',
    contact_name: 'Sherwood Maggio',
    contact_number: '601.753.2847',
    contact_email: 'valentina68@langworth.net',
    tags: {
      category: [
        {
          id: 3,
          name: 'Category One',
          slug: 'category-one',
        },
        {
          id: 4,
          name: 'Category Two',
          slug: 'category-two',
        },
      ],
      audience: [
        {
          id: 1,
          name: 'Student',
          slug: 'student',
        },
        {
          id: 2,
          name: 'Faculty',
          slug: 'faculty',
        },
      ],
    },
    multiday: true,
  },
  {
    id: 3,
    created_at: '2022-11-24T02:59:34.000000Z',
    updated_at: '2022-11-24T02:59:54.000000Z',
    user_id: 100292661,
    title: 'Title Of Champions 2',
    link: '#',
    slug: 'title-of-champions-2',
    featured_image: '',
    host_org: 'My Organization',
    content: '<p>This is a description</p>',
    start_date: '2022-11-28 10:45:00',
    end_date: '2022-11-29 11:45:00',
    on_campus: true,
    on_campus_building: 'Robertson Hall',
    on_campus_room_number: '405A',
    event_address: '1125 Colonel By Drive, Ottawa, ON, K1S 5B6',
    event_latitude: '45.3858581',
    event_longitude: '-75.6950041168868',
    registration: true,
    featured: false,
    registration_url: 'http://register.com',
    cost: '199.99',
    contact_name: 'Mike Contact',
    contact_number: '613-266-2628',
    contact_email: 'mike@contact.com',
    multiday: true,
    tags: {
      category: [
        {
          id: 3,
          name: 'Category One',
          slug: 'category-one',
        },
        {
          id: 4,
          name: 'Category Two',
          slug: 'category-two',
        },
      ],
      audience: [
        {
          id: 1,
          name: 'Student',
          slug: 'student',
        },
        {
          id: 2,
          name: 'Faculty',
          slug: 'faculty',
        },
      ],
    },
  },
];
